# ============================================================================
# AUTO-GENERATED API CATALOG CONFIGURATION
# Generated by: scripts/automate-api-catalog.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
# Updated to match Kong developer.konghq.com best practices
# ============================================================================


# ============================================================================
# API: Echo Service
# ============================================================================

# API Catalog Entry
resource "konnect_api" "echo_service_api" {
  name        = "Echo Service"
  version     = "1.0.0"
  description = "A simple HTTP Request & Response Service for testing and development"
  
  labels = {
    environment = var.environment
    managed_by  = "terraform"
    automated   = "true"
    team        = "platform"
    api_type    = "rest"
  }
}

# API Version with Specification (Kong best practice)
resource "konnect_api_version" "echo_service_version" {
  api_id = konnect_api.echo_service_api.id
  spec = {
    content = file("specs/echo-service.json")
  }
  version = "1.0.0"
  
  depends_on = [konnect_api.echo_service_api]
}

# API Documentation - Getting Started
resource "konnect_api_document" "echo_service_getting_started" {
  api_id  = konnect_api.echo_service_api.id
  title   = "Getting Started with Echo Service"
  slug    = "getting-started"
  status  = "published"
  
  content = <<-EOT
    # Getting Started with Echo Service
    
    ## Overview
    A simple HTTP Request & Response Service for testing and development
    
    ## Quick Start
    
    ### 1. Authentication
    All API requests require authentication using API keys:
    - **Header name**: `apikey` or `x-api-key`
    - Include your API key in every request
    
    ### 2. Base URL
    ```
    https://your-gateway-endpoint
    ```
    
    ### 3. Making Requests
    ```bash
    curl -X GET "https://your-gateway-endpoint/path" \
      -H "apikey: YOUR_API_KEY"
    ```
    
    ## Rate Limits
    - **Standard tier**: 100 requests per minute
    - **Premium tier**: 1000 requests per minute
    
    ## Support
    Contact: api-support@example.com
  EOT
}

# API Documentation - API Reference
resource "konnect_api_document" "echo_service_api_reference" {
  api_id  = konnect_api.echo_service_api.id
  title   = "API Reference"
  slug    = "api-reference"
  status  = "published"
  
  content = <<-EOT
    # API Reference
    
    Complete API reference documentation is available in the OpenAPI specification.
    
    ## Authentication
    All endpoints require API key authentication.
    
    ## Response Formats
    All responses are in JSON format unless otherwise specified.
    
    ## Error Handling
    The API uses standard HTTP response codes:
    - `200 OK`: Successful request
    - `400 Bad Request`: Invalid request parameters
    - `401 Unauthorized`: Missing or invalid API key
    - `403 Forbidden`: Insufficient permissions
    - `429 Too Many Requests`: Rate limit exceeded
    - `500 Internal Server Error`: Server error
  EOT
}

# Gateway Service
resource "konnect_gateway_service" "echo_service_gateway_service" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Echo-Service-Service"
  protocol         = "https"
  host             = "shared-services.kong-sales-engineering.com"
  port             = 443
  path             = "/"
  
  tags = [
    "api:echo_service",
    "managed-by:terraform",
    "automated"
  ]
}

# Default Route for Gateway Service
resource "konnect_gateway_route" "echo_service_route" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Echo-Service-Route"
  protocols        = ["https", "http"]
  paths            = ["/echo_service"]
  strip_path       = true
  
  service = {
    id = konnect_gateway_service.echo_service_gateway_service.id
  }
  
  tags = [
    "api:echo_service",
    "managed-by:terraform"
  ]
}

# API Implementation - Link API to Gateway Service (Kong best practice)
resource "konnect_api_implementation" "echo_service_implementation" {
  api_id = konnect_api.echo_service_api.id
  service_reference = {
    service = {
      control_plane_id = konnect_gateway_control_plane.terraform_cp.id
      id               = konnect_gateway_service.echo_service_gateway_service.id
    }
  }
  
  depends_on = [
    konnect_api.echo_service_api,
    konnect_api_version.echo_service_version,
    konnect_gateway_control_plane.terraform_cp,
    konnect_gateway_service.echo_service_gateway_service
  ]
}

# Publish to Dev Portal (Kong best practice)
resource "konnect_api_publication" "echo_service_publication" {
  api_id     = konnect_api.echo_service_api.id
  portal_id  = konnect_portal.terraform_portal.id
  visibility = "public"
  
  depends_on = [
    konnect_api_implementation.echo_service_implementation,
    konnect_api_document.echo_service_getting_started,
    konnect_api_document.echo_service_api_reference
  ]
}


# ============================================================================
# API: Payment API
# ============================================================================

# API Catalog Entry
resource "konnect_api" "payment_api_api" {
  name        = "Payment API"
  version     = "2.0.0"
  description = "Secure payment processing API with PCI compliance"
  
  labels = {
    environment = var.environment
    managed_by  = "terraform"
    automated   = "true"
    team        = "platform"
    api_type    = "rest"
  }
}

# API Version with Specification (Kong best practice)
resource "konnect_api_version" "payment_api_version" {
  api_id = konnect_api.payment_api_api.id
  spec = {
    content = file("specs/payment-api.yaml")
  }
  version = "2.0.0"
  
  depends_on = [konnect_api.payment_api_api]
}

# API Documentation - Getting Started
resource "konnect_api_document" "payment_api_getting_started" {
  api_id  = konnect_api.payment_api_api.id
  title   = "Getting Started with Payment API"
  slug    = "getting-started"
  status  = "published"
  
  content = <<-EOT
    # Getting Started with Payment API
    
    ## Overview
    Secure payment processing API with PCI compliance
    
    ## Quick Start
    
    ### 1. Authentication
    All API requests require authentication using API keys:
    - **Header name**: `apikey` or `x-api-key`
    - Include your API key in every request
    
    ### 2. Base URL
    ```
    https://your-gateway-endpoint
    ```
    
    ### 3. Making Requests
    ```bash
    curl -X GET "https://your-gateway-endpoint/path" \
      -H "apikey: YOUR_API_KEY"
    ```
    
    ## Rate Limits
    - **Standard tier**: 100 requests per minute
    - **Premium tier**: 1000 requests per minute
    
    ## Support
    Contact: api-support@example.com
  EOT
}

# API Documentation - API Reference
resource "konnect_api_document" "payment_api_api_reference" {
  api_id  = konnect_api.payment_api_api.id
  title   = "API Reference"
  slug    = "api-reference"
  status  = "published"
  
  content = <<-EOT
    # API Reference
    
    Complete API reference documentation is available in the OpenAPI specification.
    
    ## Authentication
    All endpoints require API key authentication.
    
    ## Response Formats
    All responses are in JSON format unless otherwise specified.
    
    ## Error Handling
    The API uses standard HTTP response codes:
    - `200 OK`: Successful request
    - `400 Bad Request`: Invalid request parameters
    - `401 Unauthorized`: Missing or invalid API key
    - `403 Forbidden`: Insufficient permissions
    - `429 Too Many Requests`: Rate limit exceeded
    - `500 Internal Server Error`: Server error
  EOT
}

# Gateway Service
resource "konnect_gateway_service" "payment_api_gateway_service" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Payment-API-Service"
  protocol         = "https"
  host             = "api.payments.example.com"
  port             = 443
  path             = "/"
  
  tags = [
    "api:payment_api",
    "managed-by:terraform",
    "automated"
  ]
}

# Default Route for Gateway Service
resource "konnect_gateway_route" "payment_api_route" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Payment-API-Route"
  protocols        = ["https", "http"]
  paths            = ["/payment_api"]
  strip_path       = true
  
  service = {
    id = konnect_gateway_service.payment_api_gateway_service.id
  }
  
  tags = [
    "api:payment_api",
    "managed-by:terraform"
  ]
}

# API Implementation - Link API to Gateway Service (Kong best practice)
resource "konnect_api_implementation" "payment_api_implementation" {
  api_id = konnect_api.payment_api_api.id
  service_reference = {
    service = {
      control_plane_id = konnect_gateway_control_plane.terraform_cp.id
      id               = konnect_gateway_service.payment_api_gateway_service.id
    }
  }
  
  depends_on = [
    konnect_api.payment_api_api,
    konnect_api_version.payment_api_version,
    konnect_gateway_control_plane.terraform_cp,
    konnect_gateway_service.payment_api_gateway_service
  ]
}

# Publish to Dev Portal (Kong best practice)
resource "konnect_api_publication" "payment_api_publication" {
  api_id     = konnect_api.payment_api_api.id
  portal_id  = konnect_portal.terraform_portal.id
  visibility = "public"
  
  depends_on = [
    konnect_api_implementation.payment_api_implementation,
    konnect_api_document.payment_api_getting_started,
    konnect_api_document.payment_api_api_reference
  ]
}


# ============================================================================
# API: User Management API
# ============================================================================

# API Catalog Entry
resource "konnect_api" "user_management_api_api" {
  name        = "User Management API"
  version     = "1.2.0"
  description = "User authentication, authorization, and profile management"
  
  labels = {
    environment = var.environment
    managed_by  = "terraform"
    automated   = "true"
    team        = "platform"
    api_type    = "rest"
  }
}

# API Version with Specification (Kong best practice)
resource "konnect_api_version" "user_management_api_version" {
  api_id = konnect_api.user_management_api_api.id
  spec = {
    content = file("specs/user-management.yaml")
  }
  version = "1.2.0"
  
  depends_on = [konnect_api.user_management_api_api]
}

# API Documentation - Getting Started
resource "konnect_api_document" "user_management_api_getting_started" {
  api_id  = konnect_api.user_management_api_api.id
  title   = "Getting Started with User Management API"
  slug    = "getting-started"
  status  = "published"
  
  content = <<-EOT
    # Getting Started with User Management API
    
    ## Overview
    User authentication, authorization, and profile management
    
    ## Quick Start
    
    ### 1. Authentication
    All API requests require authentication using API keys:
    - **Header name**: `apikey` or `x-api-key`
    - Include your API key in every request
    
    ### 2. Base URL
    ```
    https://your-gateway-endpoint
    ```
    
    ### 3. Making Requests
    ```bash
    curl -X GET "https://your-gateway-endpoint/path" \
      -H "apikey: YOUR_API_KEY"
    ```
    
    ## Rate Limits
    - **Standard tier**: 100 requests per minute
    - **Premium tier**: 1000 requests per minute
    
    ## Support
    Contact: api-support@example.com
  EOT
}

# API Documentation - API Reference
resource "konnect_api_document" "user_management_api_api_reference" {
  api_id  = konnect_api.user_management_api_api.id
  title   = "API Reference"
  slug    = "api-reference"
  status  = "published"
  
  content = <<-EOT
    # API Reference
    
    Complete API reference documentation is available in the OpenAPI specification.
    
    ## Authentication
    All endpoints require API key authentication.
    
    ## Response Formats
    All responses are in JSON format unless otherwise specified.
    
    ## Error Handling
    The API uses standard HTTP response codes:
    - `200 OK`: Successful request
    - `400 Bad Request`: Invalid request parameters
    - `401 Unauthorized`: Missing or invalid API key
    - `403 Forbidden`: Insufficient permissions
    - `429 Too Many Requests`: Rate limit exceeded
    - `500 Internal Server Error`: Server error
  EOT
}

# Gateway Service
resource "konnect_gateway_service" "user_management_api_gateway_service" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "User-Management-API-Service"
  protocol         = "https"
  host             = "api.users.example.com"
  port             = 443
  path             = "/"
  
  tags = [
    "api:user_management_api",
    "managed-by:terraform",
    "automated"
  ]
}

# Default Route for Gateway Service
resource "konnect_gateway_route" "user_management_api_route" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "User-Management-API-Route"
  protocols        = ["https", "http"]
  paths            = ["/user_management_api"]
  strip_path       = true
  
  service = {
    id = konnect_gateway_service.user_management_api_gateway_service.id
  }
  
  tags = [
    "api:user_management_api",
    "managed-by:terraform"
  ]
}

# API Implementation - Link API to Gateway Service (Kong best practice)
resource "konnect_api_implementation" "user_management_api_implementation" {
  api_id = konnect_api.user_management_api_api.id
  service_reference = {
    service = {
      control_plane_id = konnect_gateway_control_plane.terraform_cp.id
      id               = konnect_gateway_service.user_management_api_gateway_service.id
    }
  }
  
  depends_on = [
    konnect_api.user_management_api_api,
    konnect_api_version.user_management_api_version,
    konnect_gateway_control_plane.terraform_cp,
    konnect_gateway_service.user_management_api_gateway_service
  ]
}

# Publish to Dev Portal (Kong best practice)
resource "konnect_api_publication" "user_management_api_publication" {
  api_id     = konnect_api.user_management_api_api.id
  portal_id  = konnect_portal.terraform_portal.id
  visibility = "public"
  
  depends_on = [
    konnect_api_implementation.user_management_api_implementation,
    konnect_api_document.user_management_api_getting_started,
    konnect_api_document.user_management_api_api_reference
  ]
}


# ============================================================================
# API: Analytics API
# ============================================================================

# API Catalog Entry
resource "konnect_api" "analytics_api_api" {
  name        = "Analytics API"
  version     = "3.0.0"
  description = "Real-time analytics and reporting API"
  
  labels = {
    environment = var.environment
    managed_by  = "terraform"
    automated   = "true"
    team        = "platform"
    api_type    = "rest"
  }
}

# API Version with Specification (Kong best practice)
resource "konnect_api_version" "analytics_api_version" {
  api_id = konnect_api.analytics_api_api.id
  spec = {
    content = file("specs/analytics-api.yaml")
  }
  version = "3.0.0"
  
  depends_on = [konnect_api.analytics_api_api]
}

# API Documentation - Getting Started
resource "konnect_api_document" "analytics_api_getting_started" {
  api_id  = konnect_api.analytics_api_api.id
  title   = "Getting Started with Analytics API"
  slug    = "getting-started"
  status  = "published"
  
  content = <<-EOT
    # Getting Started with Analytics API
    
    ## Overview
    Real-time analytics and reporting API
    
    ## Quick Start
    
    ### 1. Authentication
    All API requests require authentication using API keys:
    - **Header name**: `apikey` or `x-api-key`
    - Include your API key in every request
    
    ### 2. Base URL
    ```
    https://your-gateway-endpoint
    ```
    
    ### 3. Making Requests
    ```bash
    curl -X GET "https://your-gateway-endpoint/path" \
      -H "apikey: YOUR_API_KEY"
    ```
    
    ## Rate Limits
    - **Standard tier**: 100 requests per minute
    - **Premium tier**: 1000 requests per minute
    
    ## Support
    Contact: api-support@example.com
  EOT
}

# API Documentation - API Reference
resource "konnect_api_document" "analytics_api_api_reference" {
  api_id  = konnect_api.analytics_api_api.id
  title   = "API Reference"
  slug    = "api-reference"
  status  = "published"
  
  content = <<-EOT
    # API Reference
    
    Complete API reference documentation is available in the OpenAPI specification.
    
    ## Authentication
    All endpoints require API key authentication.
    
    ## Response Formats
    All responses are in JSON format unless otherwise specified.
    
    ## Error Handling
    The API uses standard HTTP response codes:
    - `200 OK`: Successful request
    - `400 Bad Request`: Invalid request parameters
    - `401 Unauthorized`: Missing or invalid API key
    - `403 Forbidden`: Insufficient permissions
    - `429 Too Many Requests`: Rate limit exceeded
    - `500 Internal Server Error`: Server error
  EOT
}

# Gateway Service
resource "konnect_gateway_service" "analytics_api_gateway_service" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Analytics-API-Service"
  protocol         = "https"
  host             = "api.analytics.example.com"
  port             = 443
  path             = "/"
  
  tags = [
    "api:analytics_api",
    "managed-by:terraform",
    "automated"
  ]
}

# Default Route for Gateway Service
resource "konnect_gateway_route" "analytics_api_route" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "Analytics-API-Route"
  protocols        = ["https", "http"]
  paths            = ["/analytics_api"]
  strip_path       = true
  
  service = {
    id = konnect_gateway_service.analytics_api_gateway_service.id
  }
  
  tags = [
    "api:analytics_api",
    "managed-by:terraform"
  ]
}

# API Implementation - Link API to Gateway Service (Kong best practice)
resource "konnect_api_implementation" "analytics_api_implementation" {
  api_id = konnect_api.analytics_api_api.id
  service_reference = {
    service = {
      control_plane_id = konnect_gateway_control_plane.terraform_cp.id
      id               = konnect_gateway_service.analytics_api_gateway_service.id
    }
  }
  
  depends_on = [
    konnect_api.analytics_api_api,
    konnect_api_version.analytics_api_version,
    konnect_gateway_control_plane.terraform_cp,
    konnect_gateway_service.analytics_api_gateway_service
  ]
}


# ============================================================================
# OUTPUTS
# ============================================================================

output "echo_service_api_id" {
  description = "ID of the Echo Service API"
  value       = konnect_api.echo_service_api.id
}

output "payment_api_api_id" {
  description = "ID of the Payment Api API"
  value       = konnect_api.payment_api_api.id
}

output "user_management_api_api_id" {
  description = "ID of the User Management Api API"
  value       = konnect_api.user_management_api_api.id
}

output "analytics_api_api_id" {
  description = "ID of the Analytics Api API"
  value       = konnect_api.analytics_api_api.id
}

