#!/bin/bash

# API Catalog Automation Script
# This script automates the creation of APIs in Catalog with documents, specs,
# association with Gateway Services, and publishing to Dev Portal
# Updated to match Kong developer.konghq.com best practices

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
CONFIG_FILE="${1:-config/api-catalog-config.yaml}"
SPECS_DIR="specs"
TERRAFORM_DIR="."

echo -e "${GREEN}=== Kong Konnect API Catalog Automation ===${NC}\n"

# Check if yq is installed
if ! command -v yq &> /dev/null; then
    echo -e "${RED}Error: yq is not installed. Please install yq to parse YAML files.${NC}"
    echo "Install with: brew install yq (macOS) or see https://github.com/mikefarah/yq"
    exit 1
fi

# Check if terraform is installed
if ! command -v terraform &> /dev/null; then
    echo -e "${RED}Error: terraform is not installed.${NC}"
    exit 1
fi

# Check if configuration file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}Error: Configuration file not found: $CONFIG_FILE${NC}"
    exit 1
fi

echo -e "${YELLOW}Reading configuration from: $CONFIG_FILE${NC}\n"

# Parse configuration
API_COUNT=$(yq eval '.apis | length' "$CONFIG_FILE")

if [ "$API_COUNT" -eq 0 ]; then
    echo -e "${RED}No APIs found in configuration file${NC}"
    exit 1
fi

echo -e "${GREEN}Found $API_COUNT API(s) to process${NC}\n"

# Generate Terraform configuration
echo -e "${YELLOW}Generating Terraform configuration...${NC}"

cat > "${TERRAFORM_DIR}/api-catalog-generated.tf" << 'EOF'
# ============================================================================
# AUTO-GENERATED API CATALOG CONFIGURATION
# Generated by: scripts/automate-api-catalog.sh
# DO NOT EDIT MANUALLY - Changes will be overwritten
# Updated to match Kong developer.konghq.com best practices
# ============================================================================

EOF

# Track successfully processed APIs
SUCCESSFUL_APIS=()

# Process each API
for i in $(seq 0 $((API_COUNT - 1))); do
    API_NAME=$(yq eval ".apis[$i].name" "$CONFIG_FILE")
    API_VERSION=$(yq eval ".apis[$i].version" "$CONFIG_FILE")
    API_DESCRIPTION=$(yq eval ".apis[$i].description" "$CONFIG_FILE")
    SPEC_FILE=$(yq eval ".apis[$i].spec_file" "$CONFIG_FILE")
    GATEWAY_SERVICE=$(yq eval ".apis[$i].gateway_service" "$CONFIG_FILE")
    PUBLISH_TO_PORTAL=$(yq eval ".apis[$i].publish_to_portal" "$CONFIG_FILE")
    
    # Create safe resource name
    RESOURCE_NAME=$(echo "$API_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '_' | tr '-' '_')
    
    echo -e "${GREEN}Processing API: $API_NAME (v$API_VERSION)${NC}"
    
    # Check if spec file exists
    if [ ! -f "$SPECS_DIR/$SPEC_FILE" ]; then
        echo -e "${RED}  Error: Spec file not found: $SPECS_DIR/$SPEC_FILE${NC}"
        continue
    fi
    
    # Generate Terraform configuration for this API
    cat >> "${TERRAFORM_DIR}/api-catalog-generated.tf" << EOF

# ============================================================================
# API: $API_NAME
# ============================================================================

# API Catalog Entry
resource "konnect_api" "${RESOURCE_NAME}_api" {
  name        = "$API_NAME"
  version     = "$API_VERSION"
  description = "$API_DESCRIPTION"
  
  labels = {
    environment = var.environment
    managed_by  = "terraform"
    automated   = "true"
    team        = "platform"
    api_type    = "rest"
  }
}

# API Version with Specification (Kong best practice)
resource "konnect_api_version" "${RESOURCE_NAME}_version" {
  api_id = konnect_api.${RESOURCE_NAME}_api.id
  spec = {
    content = file("$SPECS_DIR/$SPEC_FILE")
  }
  version = "$API_VERSION"
  
  depends_on = [konnect_api.${RESOURCE_NAME}_api]
}

# API Documentation - Getting Started
resource "konnect_api_document" "${RESOURCE_NAME}_getting_started" {
  api_id  = konnect_api.${RESOURCE_NAME}_api.id
  title   = "Getting Started with $API_NAME"
  slug    = "getting-started"
  status  = "published"
  
  content = <<-EOT
    # Getting Started with $API_NAME
    
    ## Overview
    $API_DESCRIPTION
    
    ## Quick Start
    
    ### 1. Authentication
    All API requests require authentication using API keys:
    - **Header name**: \`apikey\` or \`x-api-key\`
    - Include your API key in every request
    
    ### 2. Base URL
    \`\`\`
    https://your-gateway-endpoint
    \`\`\`
    
    ### 3. Making Requests
    \`\`\`bash
    curl -X GET "https://your-gateway-endpoint/path" \\
      -H "apikey: YOUR_API_KEY"
    \`\`\`
    
    ## Rate Limits
    - **Standard tier**: 100 requests per minute
    - **Premium tier**: 1000 requests per minute
    
    ## Support
    Contact: api-support@example.com
  EOT
}

# API Documentation - API Reference
resource "konnect_api_document" "${RESOURCE_NAME}_api_reference" {
  api_id  = konnect_api.${RESOURCE_NAME}_api.id
  title   = "API Reference"
  slug    = "api-reference"
  status  = "published"
  
  content = <<-EOT
    # API Reference
    
    Complete API reference documentation is available in the OpenAPI specification.
    
    ## Authentication
    All endpoints require API key authentication.
    
    ## Response Formats
    All responses are in JSON format unless otherwise specified.
    
    ## Error Handling
    The API uses standard HTTP response codes:
    - \`200 OK\`: Successful request
    - \`400 Bad Request\`: Invalid request parameters
    - \`401 Unauthorized\`: Missing or invalid API key
    - \`403 Forbidden\`: Insufficient permissions
    - \`429 Too Many Requests\`: Rate limit exceeded
    - \`500 Internal Server Error\`: Server error
  EOT
}

EOF

    # Add Gateway Service association if specified
    if [ "$GATEWAY_SERVICE" != "null" ] && [ -n "$GATEWAY_SERVICE" ]; then
        GATEWAY_SERVICE_NAME=$(echo "${API_NAME}-Service" | tr ' ' '-')
        GATEWAY_ROUTE_NAME=$(echo "${API_NAME}-Route" | tr ' ' '-')
        cat >> "${TERRAFORM_DIR}/api-catalog-generated.tf" << EOF
# Gateway Service
resource "konnect_gateway_service" "${RESOURCE_NAME}_gateway_service" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "$GATEWAY_SERVICE_NAME"
  protocol         = "https"
  host             = "$GATEWAY_SERVICE"
  port             = 443
  path             = "/"
  
  tags = [
    "api:${RESOURCE_NAME}",
    "managed-by:terraform",
    "automated"
  ]
}

# Default Route for Gateway Service
resource "konnect_gateway_route" "${RESOURCE_NAME}_route" {
  control_plane_id = konnect_gateway_control_plane.terraform_cp.id
  name             = "$GATEWAY_ROUTE_NAME"
  protocols        = ["https", "http"]
  paths            = ["/${RESOURCE_NAME}"]
  strip_path       = true
  
  service = {
    id = konnect_gateway_service.${RESOURCE_NAME}_gateway_service.id
  }
  
  tags = [
    "api:${RESOURCE_NAME}",
    "managed-by:terraform"
  ]
}

# API Implementation - Link API to Gateway Service (Kong best practice)
resource "konnect_api_implementation" "${RESOURCE_NAME}_implementation" {
  api_id = konnect_api.${RESOURCE_NAME}_api.id
  service_reference = {
    service = {
      control_plane_id = konnect_gateway_control_plane.terraform_cp.id
      id               = konnect_gateway_service.${RESOURCE_NAME}_gateway_service.id
    }
  }
  
  depends_on = [
    konnect_api.${RESOURCE_NAME}_api,
    konnect_api_version.${RESOURCE_NAME}_version,
    konnect_gateway_control_plane.terraform_cp,
    konnect_gateway_service.${RESOURCE_NAME}_gateway_service
  ]
}

EOF
    fi
    
    # Add Portal publication if enabled
    if [ "$PUBLISH_TO_PORTAL" = "true" ]; then
        cat >> "${TERRAFORM_DIR}/api-catalog-generated.tf" << EOF
# Publish to Dev Portal (Kong best practice)
resource "konnect_api_publication" "${RESOURCE_NAME}_publication" {
  api_id     = konnect_api.${RESOURCE_NAME}_api.id
  portal_id  = konnect_portal.terraform_portal.id
  visibility = "public"
  
  depends_on = [
    konnect_api_implementation.${RESOURCE_NAME}_implementation,
    konnect_api_document.${RESOURCE_NAME}_getting_started,
    konnect_api_document.${RESOURCE_NAME}_api_reference
  ]
}

EOF
    fi
    
    echo -e "${GREEN}  ✓ Generated Terraform configuration${NC}"
    
    # Track successful processing
    SUCCESSFUL_APIS+=("$RESOURCE_NAME")
done

# Add outputs section - only for successfully processed APIs
cat >> "${TERRAFORM_DIR}/api-catalog-generated.tf" << 'EOF'

# ============================================================================
# OUTPUTS
# ============================================================================

EOF

for RESOURCE_NAME in "${SUCCESSFUL_APIS[@]}"; do
    # Get original API name from resource name
    API_NAME=$(echo "$RESOURCE_NAME" | tr '_' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
    
    cat >> "${TERRAFORM_DIR}/api-catalog-generated.tf" << EOF
output "${RESOURCE_NAME}_api_id" {
  description = "ID of the $API_NAME API"
  value       = konnect_api.${RESOURCE_NAME}_api.id
}

EOF
done

echo -e "\n${GREEN}=== Terraform configuration generated successfully ===${NC}"
echo -e "${YELLOW}Generated file: ${TERRAFORM_DIR}/api-catalog-generated.tf${NC}\n"

# Ask user to review before applying
echo -e "${YELLOW}Review the generated Terraform configuration before applying.${NC}"
read -p "Do you want to run 'terraform plan' now? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "\n${YELLOW}Running terraform init...${NC}"
    terraform -chdir="$TERRAFORM_DIR" init
    
    echo -e "\n${YELLOW}Running terraform plan...${NC}"
    terraform -chdir="$TERRAFORM_DIR" plan
    
    echo -e "\n${YELLOW}Do you want to apply these changes?${NC}"
    read -p "Run 'terraform apply'? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        terraform -chdir="$TERRAFORM_DIR" apply
        echo -e "\n${GREEN}=== API Catalog automation completed successfully! ===${NC}"
    else
        echo -e "\n${YELLOW}Skipped terraform apply. Run manually when ready.${NC}"
    fi
else
    echo -e "\n${YELLOW}Skipped terraform plan. Review the generated configuration and run manually.${NC}"
fi

echo -e "\n${GREEN}Done!${NC}"
